### ISSUE TITLE
Chapter05 Recipe04 testing thread-safe in main function

### ISSUE THREAD

**Issue by YanyangChen** [PacktPublishing/Advanced-CPP-Programming-CookBook#2]
In main function, the "s.push(4)..." would make more sense if it is replaced by "std::thread t1( [&]{ s.push(4) };); t1.join()", all the way to "std::thread t6( [&]{ s.push(42) };); t6.join()", since we might use multi-threaded execution to test if a class is thread-safe.

**Comment by sonam-packt** [comment]
@YanyangChen is the existing one gives any error?

**Comment by YanyangChen** [comment]
No, it doesn't show any error, but it's testing a thread-safe concept without using any thread execution(instead, it used a 
non-threaded procedural execution), which doesn't prove the concept it's about to demonstrate.

**Comment by rianquinn** [comment]
@YanyangChen Good point. I try to keep examples as simple as possible so that readers don't get lost in the example trying to figure out what I am trying to show vs what is there as "scaffolding". In this case, I would agree that adding some threads to this would further demonstrate the point without adding to much additional noise.

**Comment by sonam-packt** [comment]
@YanyangChen Thank you for suggesting.

**Comment by YanyangChen** [comment]
Thank you, glad it helped : )
